import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@/shared/styles/global.css';

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin'],
	weight: ['400', '700'],
});

export const metadata: Metadata = {
	title: 'Inson | Страховая компания',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={roboto.variable}>{children}</body>
		</html>
	);
}
